import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import { fileURLToPath } from 'url';
import pkg from '../package.json' with { type: 'json' };
const dir = fileURLToPath(new URL('.', import.meta.url));
const { version: currentVersion } = pkg;
console.log(`Current version: ${currentVersion}`);
const targetPath = resolve(resolve(dir, '..'), 'dist', 'index.html');
let target = readFileSync(targetPath, 'utf-8');
target = target.replaceAll('$VERSION$', currentVersion);
target = target.replaceAll('href="/utils/style.css"', 'href="./utils/style.css?v=2"');
target = target.replaceAll('href="/src/style.css"', 'href="./style.css?v=2"');
target = target.replaceAll('src="/utils/main.js"', 'src="./utils/main.js?v=2"');
target = target.replaceAll('src="/src/index.ts"', `src="./script-${currentVersion}.js?v=2"`);
target = target.replaceAll('href="/service-worker.js"', 'href="./service-worker.js"');
target = target.replaceAll('href="/412.html"', 'href="./412.html"');
writeFileSync(targetPath, target, 'utf-8');
console.log('Updated successfully.');
